groups:
- name: self-update
  jobs:
  - self-update

resource_types:
- name: pull-request
  type: registry-image
  source:
    repository: teliaoss/github-pr-resource

resources:
  - name: tech-ops
    type: git
    source:
      uri: https://github.com/alphagov/tech-ops.git

  - name: govwifi-database-backup
    type: git
    source:
      uri: https://github.com/alphagov/govwifi-database-backup.git

  - name: pull-request
    type: pull-request
    check_every: 1m
    source:
      repository: alphagov/govwifi-database-backup
      access_token: ((github-access-token))

jobs:
  - name: self-update
    serial: true
    plan:
    - get: tech-ops
      params:
        submodules: none
    - get: govwifi-database-backup
      trigger: true
    - task: set-pipelines
      file: tech-ops/ci/tasks/self-updating-pipeline.yaml
      input_mapping: {repository: govwifi-database-backup}
      params:
        CONCOURSE_TEAM: govwifi
        CONCOURSE_PASSWORD: ((readonly_local_user_password))
        PIPELINE_PATH: ci/pipelines/pr.yml
        PIPELINE_NAME: database-backup-pr
