name: govwifi-database-backup test
on:
  push:
    branches:
      - improve-logging-4-broken-test
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test
